name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Install Solhint
        run: npm install -g solhint
        
      - name: Lint Solidity
        run: solhint 'Assessment3.sol'
        
      - name: Setup Hardhat environment
        run: |
          npm install --save-dev hardhat @nomiclabs/hardhat-waffle @nomiclabs/hardhat-ethers ethereum-waffle ethers chai
          mkdir -p test
          mkdir -p contracts
          cp Assessment3.sol contracts/
          
      - name: Copy test file
        run: |
          mkdir -p test
          cat > test/AidChain-test.js << 'EOL'
          const { expect } = require("chai");
          const { ethers } = require("hardhat");

          describe("AidChain Contracts", function () {
            // 기본 테스트 - 컴파일만 확인
            it("Should compile the contracts", async function () {
              console.log("Contracts compile successfully");
              expect(true).to.equal(true);
            });
          });
          EOL
          
      - name: Run Hardhat tests
        run: npx hardhat test
        
      - name: Notify test completion
        run: echo "All tests passed! Vercel will handle the deployment automatically." 